config/routes.rb
Rails.application.routes.draw do
  scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
    root to: 'static_pages#home'
    resources :compras
    resources :produtos
    resources :vendedores
  end
  get '*path', to: redirect("/#{I18n.default_locale}/%{path}"), constraints: lambda { |req| !req.path.starts_with? "/#{I18n.default_locale}/" }
  get '', to: redirect("/#{I18n.default_locale}")
end

app/models/compra.rb
class Compra < ActiveRecord::Base
  belongs_to :vendedor
  has_and_belongs_to_many :produtos
  validates :cliente_nome, presence: true, length: { maximum: 50 }
  validates :vendedor_id, presence: true
end

app/models/produto.rb
class Produto < ActiveRecord::Base
  enum categoria: [:limpeza, :decoração, :eletronico]
  has_and_belongs_to_many :compras
  validates :descricao, presence: true, uniqueness: true, length: { maximum: 255 }
  validates :valor, presence: true
  validates :categoria, presence: true
end

app/models/vendedor.rb
class Vendedor < ActiveRecord::Base
  has_many :compras
  validates :nome, presence: true, length: { maximum: 50 }
  validates :matricula, presence: true, uniqueness: true, length: { maximum: 10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :set_locale

private

  def set_locale
    I18n.locale = params[:locale] if params[:locale].present?
  end

  def default_url_options(options = {})
    {locale: I18n.locale}
  end
end

app/controllers/compras_controller.rb
class ComprasController < ApplicationController
  before_action :set_compra, only: [:show, :edit, :update, :destroy]

  # GET /compras
  # GET /compras.json
  def index
    @compras = Compra.all
  end

  # GET /compras/1
  # GET /compras/1.json
  def show
  end

  # GET /compras/new
  def new
    @compra = Compra.new
  end

  # GET /compras/1/edit
  def edit
  end

  # POST /compras
  # POST /compras.json
  def create
    @compra = Compra.new(compra_params)

    respond_to do |format|
      if @compra.save
        format.html { redirect_to @compra, notice: 'Compra was successfully created.' }
        format.json { render :show, status: :created, location: @compra }
      else
        format.html { render :new }
        format.json { render json: @compra.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /compras/1
  # PATCH/PUT /compras/1.json
  def update
    respond_to do |format|
      if @compra.update(compra_params)
        format.html { redirect_to @compra, notice: 'Compra was successfully updated.' }
        format.json { render :show, status: :ok, location: @compra }
      else
        format.html { render :edit }
        format.json { render json: @compra.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /compras/1
  # DELETE /compras/1.json
  def destroy
    @compra.destroy
    respond_to do |format|
      format.html { redirect_to compras_url, notice: 'Compra was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_compra
      @compra = Compra.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def compra_params
      params.require(:compra).permit(:cliente_nome, :vendedor_id)
    end
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  before_action :set_produto, only: [:show, :edit, :update, :destroy]

  # GET /produtos
  # GET /produtos.json
  def index
    @produtos = Produto.all
  end

  # GET /produtos/1
  # GET /produtos/1.json
  def show
  end

  # GET /produtos/new
  def new
    @produto = Produto.new
  end

  # GET /produtos/1/edit
  def edit
  end

  # POST /produtos
  # POST /produtos.json
  def create
    @produto = Produto.new(produto_params)

    respond_to do |format|
      if @produto.save
        format.html { redirect_to @produto, notice: 'Produto was successfully created.' }
        format.json { render :show, status: :created, location: @produto }
      else
        format.html { render :new }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /produtos/1
  # PATCH/PUT /produtos/1.json
  def update
    respond_to do |format|
      if @produto.update(produto_params)
        format.html { redirect_to @produto, notice: 'Produto was successfully updated.' }
        format.json { render :show, status: :ok, location: @produto }
      else
        format.html { render :edit }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produtos/1
  # DELETE /produtos/1.json
  def destroy
    @produto.destroy
    respond_to do |format|
      format.html { redirect_to produtos_url, notice: 'Produto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produto
      @produto = Produto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def produto_params
      params.require(:produto).permit(:descrição, :valor, :categoria)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/vendedores_controller.rb
class VendedoresController < ApplicationController
  before_action :set_vendedor, only: [:show, :edit, :update, :destroy]

  # GET /vendedores
  # GET /vendedores.json
  def index
    @vendedores = Vendedor.all
  end

  # GET /vendedores/1
  # GET /vendedores/1.json
  def show
  end

  # GET /vendedores/new
  def new
    @vendedor = Vendedor.new
  end

  # GET /vendedores/1/edit
  def edit
  end

  # POST /vendedores
  # POST /vendedores.json
  def create
    @vendedor = Vendedor.new(vendedor_params)

    respond_to do |format|
      if @vendedor.save
        format.html { redirect_to @vendedor, notice: 'Vendedor was successfully created.' }
        format.json { render :show, status: :created, location: @vendedor }
      else
        format.html { render :new }
        format.json { render json: @vendedor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vendedores/1
  # PATCH/PUT /vendedores/1.json
  def update
    respond_to do |format|
      if @vendedor.update(vendedor_params)
        format.html { redirect_to @vendedor, notice: 'Vendedor was successfully updated.' }
        format.json { render :show, status: :ok, location: @vendedor }
      else
        format.html { render :edit }
        format.json { render json: @vendedor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vendedores/1
  # DELETE /vendedores/1.json
  def destroy
    @vendedor.destroy
    respond_to do |format|
      format.html { redirect_to vendedores_url, notice: 'Vendedor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vendedor
      @vendedor = Vendedor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vendedor_params
      params.require(:vendedor).permit(:nome, :matricula)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/compras_helper.rb
module ComprasHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/helpers/statis_pages_helper.rb
module StatisPagesHelper
end

app/helpers/vendedores_helper.rb
module VendedoresHelper
end

app/views/compras/_form.html.haml
= form_for(@compra) do |f|
  - if @compra.errors.any?
    #error_explanation
      %h2
        = pluralize(@compra.errors.count, "error")
        prohibited this compra from being saved:
      %ul
        - @compra.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :cliente_nome
    %br
      = f.text_field :cliente_nome
  .field
    = f.label :vendedor_id
    %br
      = f.text_field :vendedor_id
  .actions
    = f.submit "#{t("botao.salvar")}", class: "btn btn-primary"

app/views/compras/edit.html.haml
%h1
  = t(".titulo")
.row
  .col-md-6.col-md-offset-3
    = render 'form'
    = button_to t("botao.ver"), @compra, class: "btn btn-default", method: :get
    = button_to t("botao.voltar"), compras_path, class: "btn btn-default", method: :get

app/views/compras/index.html.haml
%p#notice= notice
%h1
  = t(".titulo")
.row
  .col-md-6.col-md-offset-3
    %table.table.table-bordered
      %thead
        %tr
          %th
            = Compra.human_attribute_name(:cliente_nome)
          %th
            = Compra.human_attribute_name(:vendedor_id)
          %th
            = t("mensagem.data_compra")
          %th
            = t("compras.quant_produtos")
          %th{:colspan => "3"}
      %tbody
        - @compras.each do |compra|
          %tr
            %td= compra.cliente_nome
            %td= compra.vendedor_id
            %td= compra.created_at.strftime("%d %b. %Y")
            %td= compra.produtos.count
            %td= link_to t("link.ver"), compra
            %td= link_to t("link.editar"), edit_compra_path(compra)
            %td= link_to t("link.deletar"), compra, method: :delete, data: { confirm: "#{t("confirmar")}" }
    %br
      = button_to t("botao.nova_compra"), new_compra_path, class: "btn btn-primary", method: :get

app/views/compras/new.html.haml
%h1
  = t(".titulo")
.row
  .col-md-6.col-md-offset-3
    = render 'form'
    = button_to t("botao.voltar"), compras_path, class: "btn btn-default", method: :get

app/views/compras/show.html.haml
%p#notice= notice
.row
  .col-md-6.col-md-offset-3
    %p
      %strong
        = Compra.human_attribute_name(:cliente_nome)
      = @compra.cliente_nome
    %p
      %strong
        = Compra.human_attribute_name(:vendedor_id)
      = @compra.vendedor_id
    %p
      %strong
        = t("mensagem.data_compra")
    %p
      %strong
        = t("compras.quant_produtos")
      = @compra.produtos.count
    = button_to t("botao.editar"), edit_compra_path(@compra), class: "btn btn-primary", method: :get
    = button_to t("botao.voltar"), compras_path, class: "btn btn-default", method: :get

app/views/layouts/_footer.html.haml
%footer.footer
  %small
    © Shop FFIT 2015 by
    %a{:href => "https://github.com/felipedaraujo"} Felipe de Araújo
  %nav
    %ul
      %li= link_to_unless_current t(".lingua.portugues"), locale: "pt-BR"
      %li= link_to_unless_current t(".lingua.ingles"), locale: "en"

app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top.navbar-default
  .container
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to "Shop FFIT", root_path, id: 'logo'
    #navbar-collapse.collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        %li= link_to "Home",                root_path
        %li= link_to t(".menu.compras"),    compras_path
        %li= link_to t(".menu.produtos"),   produtos_path
        %li= link_to t(".menu.vendedores"), vendedores_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Shop FFIT

    %meta{:content => "width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no", :name => "viewport"}

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'layouts/header'
    .container
      = yield
      = render 'layouts/footer'

app/views/produtos/_form.html.haml
= form_for(@produto) do |f|
  - if @produto.errors.any?
    #error_explanation
      %h2
        = pluralize(@produto.errors.count, "error")
        prohibited this produto from being saved:
      %ul
        - @produto.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :descricao
    %br
      = f.text_field :descricao
  .field
    = f.label :valor
    %br
      = f.text_field :valor
  .field
    = f.label :categoria
    %br
      = f.number_field :categoria
  .actions
    = f.submit "#{t("botao.salvar")}", class: "btn btn-primary"

app/views/produtos/edit.html.haml
%h1
  = t(".titulo")
.row
  .col-md-6.col-md-offset-3
    = render 'form'
    = button_to t("botao.ver"), @produto, class: "btn btn-default", method: :get
    = button_to t("botao.voltar"), produtos_path, class: "btn btn-default", method: :get

app/views/produtos/index.html.haml
%p#notice= notice
%h1
  = t(".titulo")
.row
  .col-md-6.col-md-offset-3
    %table.table.table-bordered
      %thead
        %tr
          %th
            = Produto.human_attribute_name(:descricao)
          %th
            = Produto.human_attribute_name(:valor)
          %th
            = Produto.human_attribute_name(:categoria)
          %th{:colspan => "3"}
      %tbody
        - @produtos.each do |produto|
          %tr
            %td= produto.descricao
            %td= number_with_precision(produto.valor, :precision => 2)
            %td= produto.categoria
            %td= link_to t("link.ver"), produto
            %td= link_to t("link.editar"), edit_produto_path(produto)
            %td= link_to t("link.deletar"), produto, method: :delete, data: { confirm: "#{t("confirmar")}" }
    %br
      = button_to t("botao.novo_produto"), new_produto_path, class: "btn btn-primary", method: :get

app/views/produtos/new.html.haml
%h1
  =t(".titulo")
.row
  .col-md-6.col-md-offset-3
    = render 'form'
    = button_to t("botao.voltar"), produtos_path, class: "btn btn-default", method: :get

app/views/produtos/show.html.haml
%p#notice= notice
.row
  .col-md-6.col-md-offset-3
    %p
      %strong
        = Produto.human_attribute_name(:descricao)
      = @produto.descricao
    %p
      %strong
        = Produto.human_attribute_name(:valor)
      = number_with_precision(@produto.valor, :precision => 2)
    %p
      %strong
        = Produto.human_attribute_name(:categoria)
      = @produto.categoria
    = button_to t("botao.editar"), edit_produto_path(@produto), class: "btn btn-primary", method: :get
    = button_to t("botao.voltar"), produtos_path, class: "btn btn-default", method: :get

app/views/static_pages/home.html.haml
.center.jumbotron
  %h1
    = t(".titulo")
  %h2
    = t(".paragrafo")

  = link_to t(".bitbucket"), 'https://bitbucket.org/felipedaraujo/shop-ffit', class: "btn btn-lg btn-primary"

app/views/vendedores/_form.html.haml
= form_for(@vendedor) do |f|
  - if @vendedor.errors.any?
    #error_explanation
      %h2
        = pluralize(@vendedor.errors.count, "error")
        prohibited this vendedor from being saved:
      %ul
        - @vendedor.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :nome
    %br
      = f.text_field :nome
  .field
    = f.label :matricula
    %br
      = f.number_field :matricula
  .actions
    = f.submit "#{t("botao.salvar")}", class: "btn btn-primary"

app/views/vendedores/edit.html.haml
%h1
  = t(".titulo")
.row
  .col-md-6.col-md-offset-3
    = render 'form'
    = button_to t("botao.ver"), @vendedor, class: "btn btn-default", method: :get
    = button_to t("botao.voltar"), vendedores_path, class: "btn btn-default", method: :get

app/views/vendedores/index.html.haml
%p#notice= notice
%h1
  = t(".titulo")
.row
  .col-md-6.col-md-offset-3
    %table.table.table-bordered
      %thead
        %tr
          %th
            = Vendedor.human_attribute_name(:nome)
          %th
            = Vendedor.human_attribute_name(:matricula)
          %th{:colspan => "3"}
      %tbody
        - @vendedores.each do |vendedor|
          %tr
            %td= vendedor.nome
            %td= vendedor.matricula
            %td= link_to t("link.ver"), vendedor
            %td= link_to t("link.editar"), edit_vendedor_path(vendedor)
            %td= link_to t("link.deletar"), vendedor, method: :delete, data: { confirm: "#{t("confirmar")}" }
    %br
      = button_to t("botao.novo_vendedor"), new_vendedor_path, class: "btn btn-primary", method: :get

app/views/vendedores/new.html.haml
%h1
  = t(".titulo")
.row
  .col-md-6.col-md-offset-3
    = render 'form'
    = button_to t("botao.voltar"), vendedores_path, class: "btn btn-default", method: :get

app/views/vendedores/show.html.haml
%p#notice= notice
.row
  .col-md-6.col-md-offset-3
    %p
      %strong
        = Vendedor.human_attribute_name(:nome)
      = @vendedor.nome
    %p
      %strong
        = Vendedor.human_attribute_name(:matricula)
      = @vendedor.matricula
    = button_to t("botao.editar"), edit_vendedor_path(@vendedor), class: "btn btn-primary", method: :get
    = button_to t("botao.voltar"), vendedores_path, class: "btn btn-default", method: :get